### ISSUE TITLE
[Bug]:  Unable to start thor

### ISSUE THREAD

**Issue by Yuzzay** [ethical-haquer/Thor_GUI#11]
### What happened?

When I click on "start Thor" flash utility (1.0.4) nothing happens. I checked the the terminal and saw this  error:

An Exception occurred in start_thor:
The command was not found or was not executable: /home/yusufjibrahim08/Thor/linux-x64/TheAirBlow.Thor.Shell.

What could be the cause of this issue and how can I solve it. Im a total noob at this. I just want to flash a firmware on my SM-N960F

Also I noticed that "Thor GUI version" isnt showing up at the top of the interface, like it does in your screenshots and usage tutorial video. Could this perhaps be the issue? How can I solve it. Im using a chromebook with Linux tools 

![Screenshot 2024-01-11 20 18 28](https://github.com/ethical-haquer/Thor_GUI/assets/156359624/ea914d71-76fa-4724-ad20-275e191155dc)

### Thor GUI version

Alpha v0.4.4

### Thor Flash Utility version

1.0.4

**Comment by Yuzzay** [comment]
Im convinced that I messed up somewhere in the installation process. It would mean the world to me if you could help me get this fixed so I can flash a firmware on my bricked phone.

**Comment by justaCasualCoder** [comment]
Hey @Yuzzay! I was having a similar error a while back. For me the issue was I did not have [DotNet 7 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/7.0). Try using `wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh` to download the linux installer. Then `bash dotnet-install.sh` to run it.

**Comment by Yuzzay** [comment]
Hey @justaCasualCoder how do I do that? Im pretty new to this code/terminal stuff. Could you please type down a noob-friendly step by step guide on how I can solve this issue. I would really appreaciate it!! Many thanks in advance!!

**Comment by justaCasualCoder** [comment]
Try this (Run all of this in the same terminal that you ran `python3 thor-gui.py` in):
- Install `wget` (To download the installer):
```bash
sudo apt install wget -y
```
- Download & Run the installer (For DOTNET 7):
```bash
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh && bash dotnet-install.sh --channel 7.0
```
- Test DOTNET:
```bash
dotnet --info
```
- Try running Thor GUI again:
```bash
python3 thor-gui.py
```
@ethical-haquer Maybe add something like this to the `README`?

**Comment by Yuzzay** [comment]
@justaCasualCoder All the steps worked fine except for step 3 "Test DOTNET". When I type the command "dotnet --info" it says  "-bash: dotnet: command not found". I tried running Thor GUI anyways but it seems that the problem still presists.

heres a screenshoot of how it looks:

![Screenshot 2024-01-12 15 35 31](https://github.com/ethical-haquer/Thor_GUI/assets/156359624/c16b5a97-e41c-4935-a29c-24b4472fea64)

**Comment by Yuzzay** [comment]
@justaCasualCoder Am I doing something wrong?

**Comment by Yuzzay** [comment]
Hey @justaCasualCoder  I made some progress. The error code went from showing up in the terminal only to now directly showing up in Thor GUI. Is this a good sign? lol
![Screenshot 2024-01-12 15 59 56](https://github.com/ethical-haquer/Thor_GUI/assets/156359624/b9d939a9-2d0f-4931-b1a6-01a715d77231)

**Comment by justaCasualCoder** [comment]
I don't know much about chrome book's linux tools, but could you post the output of this? (This will get your Linux OS version and save the DOTNET installer output to a log)
```bash
cat /etc/os-release
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
bash dotnet-install.sh --channel 7.0 | tee dotnet_install_log.txt
```
Then upload dotnet_install_log.txt. You could also try restarting...

**Comment by Yuzzay** [comment]
@justaCasualCoder heres what  I got:

cat /etc/os-release
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
bash dotnet-install.sh --channel 7.0 | tee dotnet_install_log.txt

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
--2024-01-12 16:49:04--  https://dot.net/v1/dotnet-install.sh
Resolving dot.net (dot.net)... 20.236.44.162, 20.231.239.246, 20.112.250.133, ...
Connecting to dot.net (dot.net)|20.236.44.162|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh [following]
--2024-01-12 16:49:06--  https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
Resolving dotnet.microsoft.com (dotnet.microsoft.com)... 2620:1ec:bdf::53, 2620:1ec:46::53, 13.107.213.53, ...
Connecting to dotnet.microsoft.com (dotnet.microsoft.com)|2620:1ec:bdf::53|:443... connected.
HTTP request sent, awaiting response... 200 OK
Cookie coming from dotnet.microsoft.com attempted to set domain to dotnetwebsite.azurewebsites.net
Cookie coming from dotnet.microsoft.com attempted to set domain to dotnetwebsite.azurewebsites.net
Length: 61896 (60K) [application/x-sh]
Saving to: ‘dotnet-install.sh’

dotnet-install.sh       100%[==============================>]  60.45K  --.-KB/s    in 0.1s    

2024-01-12 16:49:08 (605 KB/s) - ‘dotnet-install.sh’ saved [61896/61896]

dotnet-install: .NET Core SDK with version '7.0.405' is already installed.

**Comment by justaCasualCoder** [comment]
Try Restarting...

**Comment by Yuzzay** [comment]
Roger that. Ill restart my whole pc and try again

**Comment by Yuzzay** [comment]
@justaCasualCoder  I can start thor now but its missing the TheAirBlow.Thor.Shell command. its basically the same problem as in the last screenshot I sent. The only thing I can do is force stop thor....

**Comment by Yuzzay** [comment]
![Screenshot 2024-01-12 17 19 30](https://github.com/ethical-haquer/Thor_GUI/assets/156359624/236fde15-2716-4ddd-8b91-a25bc437d386)

**Comment by ethical-haquer** [comment]
Alright, let me see what the issue is. :smile:

**Comment by Yuzzay** [comment]
@ethical-haquer  Dude, you're the real MVP if you help me get this fixed. Ive been struggling with it for the past 2 days haha. I was almost about to give up but seeing your comment made me feel hopeful again!!

**Comment by Yuzzay** [comment]
@ethical-haquer What I did was follow the instructions you released. I do have a file named "thor-gui-linux-v0.4.4-alpha.zip" which I extracted. Im not a linux guru so I could have messed up somewhere along the installation process. I was even struggling getting the GUI to lauch for a whole day before finally suceeding in launching it up (like in the screenshot I sent here). Could you perhaps walk be throught a step by step guide on what exactly I need to do. I can even uninstall thor and reinstall it with your guidance.

**Comment by ethical-haquer** [comment]
> @ethical-haquer What I did was follow the instructions you released. I do have a file named "thor-gui-linux-v0.4.4-alpha.zip" which I extracted. Im not a linux guru so I could have messed up somewhere along the installation process. I was even struggling getting the GUI to lauch for a whole day before finally suceeding in launching it up (like in the screenshot I sent here). Could you perhaps walk me through a step by step guide on what exactly I need to do. I can even uninstall thor and reinstall it with your guidance.

Absolutely! Could you give me a screenshot of the directory where you have the .py file located?

**Comment by ethical-haquer** [comment]
Or, if you have it in your home directory, I can just guide you through the installation process. Just let me know what you want.

**Comment by Yuzzay** [comment]
@ethical-haquer I use a chromebook with Linux development enviroment enabled so the .py file is located under "Linux files" which I guess would be the equivalant of "home"..... but im not 100% sure if thats home or not haha

**Comment by ethical-haquer** [comment]
> @ethical-haquer I use a chromebook with Linux development enviroment enabled so the .py file is located under "Linux files" which I guess would be the equivalant of "home"..... but im not 100% sure if thats home or not haha

That terminal is only for Linux, correct? If you open up a terminal, and then run "ls", what is the output?

**Comment by Yuzzay** [comment]
Im a total noob at this. I came from Windows pc and used to use odin for a long time. Thats actually how I discovered you and the Thor GUI. I read your instructions on how to use odin on linux with VM but I thought that was too much work so decided to give Thor a shot. lol

**Comment by Yuzzay** [comment]
Yes the terminal is 100% only Linux. heres the output of "ls"

AP
 BL
 CP
 CSC
 dotnet_install_log.txt
 dotnet-install.sh
 Downloads
 Heimdall-master
 Heimdall-master.zip
 help
 magisk_patched-26400_EfWI9.img
 N960FXXSAFWB3_N960FOBEAFWB1_BTE
 note9.pit
 Odin4-Linux.zip
 Oracle_VM_VirtualBox_Extension_Pack-7.0.12.vbox-extpack
 Python-3.12.1.tar.xz
 SAMFW.COM_SM-N960F_XEU_N960FXXS4CSK2_fac
 Thor_GUI-0.3.1-alpha.tar.gz
 Thor_GUI-0.3.1-alpha.zip
 Thor_GUI-0.4.3-alpha.zip
 Thor_GUI-0.4.4-alpha
 Thor_GUI-0.4.4-alpha.tar.gz
 Thor_GUI-0.4.4-alpha.zip
 thor-gui-linux-0.4.3-alpha.zip
'thor-gui-linux-v0.4 (1).4-alpha'
 thor-gui-linux-v0.4.4-alpha
 thor-gui-linux-v0.4.4-alpha.zip
 thor-gui.py
 thor-gui-settings.json
 Thor-main
 virtualbox-7.0_7.0.12-159484~Debian~bullseye_amd64.deb

**Comment by Yuzzay** [comment]
Dont judge my files!!! lol

**Comment by Yuzzay** [comment]
well, nothings happens after I type "ls"
![Screenshot 2024-01-12 18 20 19](https://github.com/ethical-haquer/Thor_GUI/assets/156359624/d5847e96-dd47-49f5-b0ba-ad4e0c4aaa95)

**Comment by Yuzzay** [comment]
Does that mean the file is empty or?

**Comment by ethical-haquer** [comment]
> Does that mean the file is empty or?

Yeah, that would mean the directory (aka folder) is empty. In a graphical file manager can you delete that folder, and then extract the "thor-gui-linux-v0.4.4-alpha.zip" file again?

**Comment by Yuzzay** [comment]
Done! this time it wasnt empty
![Screenshot 2024-01-12 18 33 27](https://github.com/ethical-haquer/Thor_GUI/assets/156359624/f5a085d9-8bdf-486f-9ead-9b80fcb65c19)

**Comment by Yuzzay** [comment]
Whats the next step. (btw I wanna thank you for doing this, You have no idea how much it means to me. Ive been struggling with this for almost 3 days now)

**Comment by ethical-haquer** [comment]
> Whats the next step.

The next thing to do is run "python3 thor-gui.py", assuming you still have that terminal open. Otherwise just cd into that directory again and then run it.

> (btw I wanna thank you for doing this, You have no idea how much it means to me. Ive been struggling with this for almost 3 days now)

Don't worry about it, I know what you're talking about. That's why I made that Odin on Linux guide, and now Thor GUI. Congrats on your first GitHub issue!
(I really do need to have Thor GUI tell the user when that exception occurs :rofl:)

I really hope this works out for you, but if not I'll be here to help. I won't be on here again till later today in the afternoon, see you!

**Comment by Yuzzay** [comment]
Okay so it seems like im back to square one lol.... 

im getting this error code when I try to start thor from within the directory.

"An Exception occurred in start_thor:
The command was not found or was not executable: /home/yusufjibrahim08/thor-gui-linux-v0.4.4-alpha/Thor/linux-x64/TheAirBlow.Thor.Shell."
![Screenshot 2024-01-12 19 29 06](https://github.com/ethical-haquer/Thor_GUI/assets/156359624/dfb31fde-bff6-4bcd-9939-232bbddda4fa)

**Comment by Yuzzay** [comment]
Man this is driving me crazy!!

**Comment by justaCasualCoder** [comment]
What is the output of `ls -la /home/yusufjibrahim08/thor-gui-linux-v0.4.4-alpha/Thor/*`? Maybe executable permissions are not set? Also you can just wait for @ethical-haquer to come back. Just thought I would try to help...

**Comment by Yuzzay** [comment]
@justaCasualCoder I appreciate you coming back to help. At this point ill take any help I can get. Heres the output:

rw-r--r-- 1 yusufjibrahim08 yusufjibrahim08 16725 Jan 12 18:30 /home/yusufjibrahim08/thor-gui-linux-v0.4.4-alpha/Thor/LICENSE
-rw-r--r-- 1 yusufjibrahim08 yusufjibrahim08  4372 Jan 12 18:30 /home/yusufjibrahim08/thor-gui-linux-v0.4.4-alpha/Thor/README.md

/home/yusufjibrahim08/thor-gui-linux-v0.4.4-alpha/Thor/linux-arm64:
total 73756
drwxr-x--x 1 yusufjibrahim08 chronos-access        42 Jan 12 18:30 .
drwxr-x--x 1 yusufjibrahim08 chronos-access        72 Jan 12 18:30 ..
-rw-r--r-- 1 yusufjibrahim08 yusufjibrahim08 75525665 Jan 12 18:30 TheAirBlow.Thor.Shell

/home/yusufjibrahim08/thor-gui-linux-v0.4.4-alpha/Thor/linux-x64:
total 67004
drwxr-x--x 1 yusufjibrahim08 chronos-access        42 Jan 12 18:30 .

**Comment by Yuzzay** [comment]
If the case is that executable permissions are not set, which im unsure of, how can I check if it is or not? And how can I set it up?

**Comment by justaCasualCoder** [comment]
Strange... It seems `TheAirBlow.Thor.Shell` file is not there for x86_64... try `cd /home/yusufjibrahim08/thor-gui-linux-v0.4.4-alpha/Thor/linux-x64 && ls -la`

**Comment by Yuzzay** [comment]
Hey you know what, you might just have cracked the issue. As far as my noob mind goes, I think youve successfully diagnosed the issue.  So the SHELL file is there but not executable. Is this correct?

**Comment by Yuzzay** [comment]
Heres the output:

total 67004
drwxr-x--x 1 yusufjibrahim08 chronos-access        42 Jan 12 18:30 .
drwxr-x--x 1 yusufjibrahim08 chronos-access        72 Jan 12 18:30 ..
-rw-r--r-- 1 yusufjibrahim08 yusufjibrahim08 68608022 Jan 12 18:30 TheAirBlow.Thor.Shell

**Comment by justaCasualCoder** [comment]
Yep! Try running `chmod -v +x /home/yusufjibrahim08/thor-gui-linux-v0.4.4-alpha/Thor/linux-x64/TheAirBlow.Thor.Shell`

**Comment by Yuzzay** [comment]
Dude.... youre a fucking GOD!!!!!!!!
![Screenshot 2024-01-12 21 15 24](https://github.com/ethical-haquer/Thor_GUI/assets/156359624/ac32e402-0a92-4cb8-bd59-9bb30e7033cc)

**Comment by Yuzzay** [comment]
I can FINALLY use Thor GUI!!!!!!!!!!
![Screenshot 2024-01-12 21 19 03](https://github.com/ethical-haquer/Thor_GUI/assets/156359624/a196e180-e011-4493-8cdf-4a3190984f3e)

**Comment by justaCasualCoder** [comment]
I am glad it is working for you!

**Comment by Yuzzay** [comment]
I can not thank you enough! Ive had a headache for 3 days trying to slove this!!!

**Comment by justaCasualCoder** [comment]
@ethical-haquer 
The issue is Fixed!

**Comment by Yuzzay** [comment]
Hey again @justaCasualCoder , Just a quick question. Why does it say "Too many arguments!" when I try to flash a firmware onto my bricked phone? This is what it says:

flashTar /home/yusufjibrahim08/SAMFW (1).COM_SM-N960F_XEU_N960FXXS4CSK2_fac
~~~~~~~~~~~~~~~~^
Too many arguments!
shell>

**Comment by Yuzzay** [comment]
Heres how it looks: 
![Screenshot 2024-01-12 22 11 12](https://github.com/ethical-haquer/Thor_GUI/assets/156359624/5a3e105c-048d-46f8-b819-29a810f3474e)

**Comment by Yuzzay** [comment]
Any idea on whats happening?

**Comment by justaCasualCoder** [comment]
@Yuzzay 
This may be another bug, but I am almost certain you just need to put `"` on each side of the path to the file. Like `"/home/yusufjibrahim08/SAMFW (1).COM_SM-N960F_XEU_N960FXXS4CSK2_fac"`. It is like this because the way Linux handles files with spaces in them. 
@ethical-haquer  
A fix in the code would be to change line 673 from  `send_command(f'flashTar {common_directory}')` to `send_command(f"flashTar '{common_directory}'")`

**Comment by Yuzzay** [comment]
@justaCasualCoder Okay so heres what I did. I deleted the firmware files that I was initially trying to flash onto my device and downloaded a new file from sammobile. I extracted it and tried flashing it. I ended up getting a new error code that says "failed to bulk read: connection timed out (110)

flashTar /home/yusufjibrahim08/N960FXXSAFWB3_N960FOBEAFWB1_EVR
~~~~~~~^
Failed to bulk read: Connection timed out (110)
shell>

**Comment by Yuzzay** [comment]
Heres how it looks on my screen:
![Screenshot 2024-01-13 01 46 56](https://github.com/ethical-haquer/Thor_GUI/assets/156359624/c3568fa4-06ef-4cda-8175-c89dd2f069ae)

**Comment by Yuzzay** [comment]
The weird thing is that I sometimes get the same error code when I try to "start odin protocol". The way around that, as ive discovered, is to turn my phone off and boot back into download mode again. However, when it comes to flashing the actual firmware, the above stated error comes up every single time. Do you have any idea what is causing the connection time out?

**Comment by Yuzzay** [comment]
Apparently Im so good at running into bugs that I think I should be promoted to an official tester of Thor GUI lol  XD

**Comment by justaCasualCoder** [comment]
Unfortunately I am not very good with Thor... This issue https://github.com/Samsung-Loki/Thor/issues/15 seems the same. I would leave this to @ethical-haquer to debug. In the meantime you could try `heimdall` with my [SamsungFlashGUI](https://github.com/justaCasualCoder/SamsungFlashGUI) (A PySide6 GUI around `heimdall`).

**Comment by Yuzzay** [comment]
Roger that. Ill wait for @ethical-haquer to help me out here. However in the meanwhile ill look into heimdall and other methods, I guess. Thank you for the links and suggestions :)

**Comment by ethical-haquer** [comment]
First of all, I'm glad you at least got Thor running @Yuzzay!
Also, thanks a ton @justaCasualCoder for helping out and pointing out the permission issue and the issue with file-paths containing a space.
As for the "Failed to bulk read: Connection timed out (110)" error, yes that is a known (and common) Thor issue: [link](https://github.com/Samsung-Loki/Thor/issues/10), [link](https://github.com/Samsung-Loki/Thor/issues/13). The only thing I can think of is to try running Thor with sudo, it's a setting called "Run Thor with sudo" in the Settings tab. If that doesn't work, then I'm not really sure what else to do.

**Comment by Yuzzay** [comment]
Well, I tried again after enabling sudo from the settings of Thor and the "Failed to bulk read: Connection timed out" error still presist. Trying other methods didnt work either.  Heimdall is equally confusing and buggy as Thor in my experience. I have to say, thank you for your time and knowledge but I have reached the limit of my patience with this project. I deeply regret ever leaving the comfort and familiarity of my windows PC and switching to Linux/chrome. It was a very foolish decision of me as ive come to find out the hard way. I have a soft bricked phone that ive been trying to restore through Linux for the past 3 days. Its was fun while it lasted and ive certainly learnt a thing or two about using terminals and running commands etc.

However, as disappointing as it is, I finally accept defeat. I will ask to borrow my friends pc tomorrow (He has a windows laptop) and just solve this issue once and for all with good ol' fashioned  Odin. These past 3 days has been an absolute nightmare, but I learnt a lot in the process, so at least I can be grateful for that.

Again, thank you  @justaCasualCoder and @ethical-haquer for your time and knowledge, it means a lot!

And last but not least, thank you for coming to my ted talk lol XD
